#ifndef NOVAC_PPPLIB_MEASUREMENT_H
#define NOVAC_PPPLIB_MEASUREMENT_H

// The various kinds of measurement modes that we have
enum MEASUREMENT_MODE {
	MODE_UNKNOWN,
	MODE_FLUX,
	MODE_WINDSPEED,
	MODE_STRATOSPHERE,
	MODE_DIRECT_SUN,
	MODE_COMPOSITION,
	MODE_LUNAR,
	MODE_TROPOSPHERE,
	MODE_MAXDOAS
};

#endif  // NOVAC_PPPLIB_MEASUREMENT_H